name: Deploy GitHub Pages

on:
  push:
    branches:
      - dev-pages
      # - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen Documentation
        run: cd doc && doxygen

      - name: Move pages
        run: mkdir -p docs && mv temp/html/* docs/ && tree .

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git branch -D gh-pages || true
          git checkout --orphan gh-pages
          git add -A
          git commit -m "Auto-deploy to GitHub Pages"
          git push -f origin gh-pages